[package]
name = "cjk-num-format"
version = "0.1.0"
entrypoint = "./src/lib.typ"
authors = ["Jeremy Gao <@wensimehrp>"]
license = "MIT"
description = "Format numbers in CJK conventions"
repository = "https://github.com/wensimehrp/cjk-num-format"
categories = ["languages", "utility", "scripting"]
disciplines = ["history", "education"]
compiler = "0.13.1"
